export type SharePermission = "read" | "write";

const FILE_ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;
const TOKEN_PATTERN = /^[A-Za-z0-9_-]{43,44}$/;

/** Liveblocks room for a file. File IDs are validated so room names can't escape their namespace. */
export function roomIdForFile(fileId: string): string {
  if (!FILE_ID_PATTERN.test(fileId)) throw new Error(`invalid file id: ${fileId}`);
  return `filebase:file:${fileId}`;
}

/** Strict permission parsing — unknown values throw instead of defaulting. */
export function normalizeSharePermission(value: unknown): SharePermission {
  if (value === "read" || value === "write") return value;
  throw new Error(`invalid share permission: ${String(value)}`);
}

/** 256-bit base64url token as generated by shares.createShare. */
export function isShareTokenFormat(token: string): boolean {
  return TOKEN_PATTERN.test(token);
}

const GUEST_FALLBACK = "Guest";

/** Display names from guests are untrusted: strip markup, bound length, never empty. */
export function sanitizeGuestName(name: unknown): string {
  const cleaned = String(name ?? "")
    .replace(/[<>&"']/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 32);
  return cleaned === "" ? GUEST_FALLBACK : cleaned;
}
